services:

  t1-backend:
    image: t1-backend:latest
    ports: 
      - 3000:3000
    environment:
      - NODE_ENV=local
      - HOST=localhost
      - PORT=3000
      - SWAGGER_PATH=docs
      - ADDRESS=http://localhost:3001
      - DB_USER=user
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_PASSWORD=12345
      - DB_NAME=hackaton

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432

    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=user
      - POSTGRES_DB=hackaton